name: Renaud Bougues
favicon: null
layout_spectrum: 0.8046323030721396
typography_spectrum: 0.4166294215247035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9877269223798066
  lightness: 0.6462700848933309
  saturation: 0.25827371375635266
  rhythmicContrast: 0.7906556006055325
purpose: []
